### ISSUE TITLE
Line 106, Should "name" be changed to "client"?

### ISSUE THREAD

**Issue by jeanim** [fzlee/namecom#3]
https://github.com/fzlee/namecom/blob/9fa818a5b965819eeaebf9b33eb528153a9fc556/namecom/bin/namecli#L106

Traceback (most recent call last):
  File "/usr/local/bin/namecli", line 112, in <module>
    cli()
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/bin/namecli", line 106, in ddns
    name.update_record(domain, record["id"], host, "A", ip)
AttributeError: 'str' object has no attribute 'update_record'

thks

**Comment by fzlee** [comment]
Please try 0.6.0 instead

**Comment by jeanim** [comment]
The default installed version of pip has been ok, thank you
